import { useState } from 'react';
import { View,TextInput,Pressable,Text,Alert,StyleSheet,useWindowDimensions,ActivityIndicator } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient'; import { Ionicons } from '@expo/vector-icons'; import { useRouter,Link } from 'expo-router'; import { useAuth } from '../src/context/AuthContext'; import { AppColors } from './theme'; import { useAppTheme } from '../src/context/ThemeContext';
export default function LoginScreen(){const router=useRouter();const {login}=useAuth();const {colors,isDark}=useAppTheme();const s=makeStyles(colors);const [email,setEmail]=useState('');const [senha,setSenha]=useState('');const [show,setShow]=useState(false);const [loading,setLoading]=useState(false);const {width}=useWindowDimensions();const mobile=width<760;
 async function entrar(){if(!email.trim()||!senha){Alert.alert('Preencha email e senha');return}setLoading(true);try{await login(email.trim(),senha);router.replace('/admin')}catch{Alert.alert('Acesso não autorizado','Confira seu email e senha.')}finally{setLoading(false)}}
 return <LinearGradient colors={isDark?['#08111D','#0C1B28','#0D2730']:['#F8FBFC','#EEF5F4','#E5F1ED']} style={s.page}><View style={[s.layout,mobile&&s.mobile]}>
  {!mobile&&<View style={s.aside}><Link href="/" asChild><Pressable style={s.brand}><View style={s.mark}><Text style={s.code}>{'<>'}</Text></View><Text style={s.brandText}>Dicionário Tech</Text></Pressable></Link><View><Text style={s.kicker}>PAINEL DE CONTEÚDO</Text><Text style={s.asideTitle}>Conhecimento bem cuidado <Text style={s.accent}>transforma.</Text></Text><Text style={s.asideText}>Revise contribuições e mantenha nosso dicionário simples, correto e acessível.</Text></View><Text style={s.asideFooter}>Lar São Francisco • 2026</Text></View>}
  <View style={s.formSide}><View style={s.card}><Link href="/" asChild><Pressable style={s.back}><Ionicons name="arrow-back" size={16} color={colors.textSecondary}/><Text style={s.backText}>Voltar ao início</Text></Pressable></Link><View style={s.lock}><Ionicons name="lock-closed" size={22} color={colors.primary}/></View><Text style={s.title}>Bem-vindo de volta</Text><Text style={s.subtitle}>Entre com suas credenciais de administrador.</Text>
   <Text style={s.label}>EMAIL</Text><View style={s.inputWrap}><Ionicons name="mail-outline" size={18} color={colors.textMuted}/><TextInput value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" placeholder="seu@email.com" placeholderTextColor={colors.textMuted} style={s.input}/></View>
   <Text style={s.label}>SENHA</Text><View style={s.inputWrap}><Ionicons name="key-outline" size={18} color={colors.textMuted}/><TextInput value={senha} onChangeText={setSenha} secureTextEntry={!show} placeholder="Sua senha" placeholderTextColor={colors.textMuted} onSubmitEditing={entrar} style={s.input}/><Pressable onPress={()=>setShow(!show)}><Ionicons name={show?'eye-off-outline':'eye-outline'} size={19} color={colors.textMuted}/></Pressable></View>
   <Pressable disabled={loading} onPress={entrar} style={({hovered,pressed})=>[s.button,hovered&&s.hover,pressed&&s.pressed]}>{loading?<ActivityIndicator color={colors.primaryText}/>:<><Text style={s.buttonText}>Entrar no painel</Text><Ionicons name="arrow-forward" size={19} color={colors.primaryText}/></>}</Pressable><Text style={s.secure}>🔒 Ambiente seguro e de acesso restrito</Text>
  </View></View>
 </View></LinearGradient>}
const makeStyles=(colors:AppColors)=>StyleSheet.create({page:{flex:1},layout:{flex:1,flexDirection:'row'},mobile:{justifyContent:'center'},aside:{flex:1,padding:52,justifyContent:'space-between',backgroundColor:colors.backgroundSoft,borderRightWidth:1,borderRightColor:colors.border},brand:{flexDirection:'row',alignItems:'center',gap:11},mark:{width:42,height:42,borderRadius:13,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},code:{color:colors.primaryText,fontSize:14,fontWeight:'900'},brandText:{color:colors.text,fontSize:17,fontWeight:'800'},kicker:{color:colors.primary,fontSize:14,fontWeight:'800',letterSpacing:1.2,marginBottom:17},asideTitle:{color:colors.text,fontSize:44,lineHeight:51,fontWeight:'900',maxWidth:520},accent:{color:colors.primary},asideText:{color:colors.textSecondary,fontSize:16,lineHeight:26,maxWidth:500,marginTop:18},asideFooter:{color:colors.textMuted,fontSize:14},formSide:{flex:1,alignItems:'center',justifyContent:'center',padding:24},card:{width:'100%',maxWidth:440,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:24,padding:30,shadowColor:'#000',shadowOpacity:.12,shadowRadius:30},back:{flexDirection:'row',alignItems:'center',gap:7,marginBottom:30},backText:{color:colors.textSecondary,fontSize:14},lock:{width:52,height:52,borderRadius:16,backgroundColor:colors.successSoft,alignItems:'center',justifyContent:'center',marginBottom:20},title:{color:colors.text,fontSize:27,fontWeight:'900'},subtitle:{color:colors.textMuted,fontSize:15,marginTop:7,marginBottom:28},label:{color:colors.textSecondary,fontSize:14,fontWeight:'800',letterSpacing:.8,marginBottom:8},inputWrap:{height:56,flexDirection:'row',alignItems:'center',gap:10,backgroundColor:colors.backgroundSoft,borderWidth:1,borderColor:colors.border,borderRadius:14,paddingHorizontal:14,marginBottom:18},input:{flex:1,color:colors.text,fontSize:15,outlineStyle:'none'} as any,button:{height:56,borderRadius:14,backgroundColor:colors.primary,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9,marginTop:4},hover:{backgroundColor:colors.primaryHover},pressed:{opacity:.75},buttonText:{color:colors.primaryText,fontSize:15,fontWeight:'800'},secure:{color:colors.textMuted,fontSize:14,textAlign:'center',marginTop:18}});
