import { useState } from 'react';
import { View,TextInput,Alert,StyleSheet,Text,Pressable,ScrollView,useWindowDimensions,ActivityIndicator } from 'react-native';
import { Ionicons } from '@expo/vector-icons'; import { db } from '../src/backend/firebaseconfig'; import { collection,addDoc } from 'firebase/firestore';
import Header from './header'; import Footer from './footer'; import { LinearGradient } from 'expo-linear-gradient'; import { colors } from './theme';
export default function SugestaoScreen(){
 const [termo,setTermo]=useState('');const [descricao,setDescricao]=useState('');const [loading,setLoading]=useState(false);const {width}=useWindowDimensions();const mobile=width<760;
 const enviar=async()=>{if(!termo.trim()||!descricao.trim()){Alert.alert('Preencha os campos','Conte qual é o termo e descreva seu significado.');return}setLoading(true);try{await addDoc(collection(db,'sugestoes'),{termo:termo.trim(),descricao:descricao.trim(),status:'pendente',data:new Date()});Alert.alert('Sugestão enviada!','Obrigado por contribuir com a comunidade.');setTermo('');setDescricao('')}catch{Alert.alert('Não foi possível enviar','Tente novamente em instantes.')}finally{setLoading(false)}};
 return <LinearGradient colors={['#07111F','#0A1C2B','#0C2530']} style={s.page}><Header/><ScrollView contentContainerStyle={s.scroll}><View style={[s.layout,mobile&&s.layoutMobile]}>
  <View style={s.copy}><View style={s.iconBox}><Ionicons name="bulb" size={24} color="#06251B"/></View><Text style={s.kicker}>CONSTRUA COM A GENTE</Text><Text style={[s.title,mobile&&s.titleMobile]}>Sentiu falta de uma <Text style={s.accent}>palavra?</Text></Text><Text style={s.subtitle}>Sua curiosidade pode ajudar outra pessoa. Sugira um termo e nossa equipe revisa antes de publicar.</Text>
   <View style={s.steps}><View style={s.step}><Text style={s.stepNumber}>01</Text><Text style={s.stepText}>Você envia a sugestão</Text></View><View style={s.step}><Text style={s.stepNumber}>02</Text><Text style={s.stepText}>Nossa equipe revisa</Text></View><View style={s.step}><Text style={s.stepNumber}>03</Text><Text style={s.stepText}>A comunidade aprende</Text></View></View>
  </View>
  <View style={s.card}><Text style={s.formTitle}>Sugerir novo termo</Text><Text style={s.formSub}>Preencha os dados abaixo. Leva menos de um minuto.</Text>
   <Text style={s.label}>NOME DO TERMO</Text><View style={s.inputWrap}><Ionicons name="code-slash-outline" size={19} color={colors.textMuted}/><TextInput value={termo} onChangeText={setTermo} placeholder="Ex.: Machine Learning" placeholderTextColor={colors.textMuted} style={s.input}/></View>
   <Text style={s.label}>EXPLICAÇÃO</Text><View style={[s.inputWrap,s.textarea]}><TextInput value={descricao} onChangeText={setDescricao} placeholder="Explique com suas próprias palavras..." placeholderTextColor={colors.textMuted} multiline textAlignVertical="top" maxLength={500} style={[s.input,s.textareaInput]}/></View><Text style={s.counter}>{descricao.length}/500</Text>
   <Pressable disabled={loading} onPress={enviar} style={({hovered,pressed})=>[s.button,hovered&&s.hover,pressed&&s.pressed]}>{loading?<ActivityIndicator color="#06251B"/>:<><Text style={s.buttonText}>Enviar para revisão</Text><Ionicons name="arrow-forward" size={19} color="#06251B"/></>}</Pressable><View style={s.note}><Ionicons name="shield-checkmark-outline" size={15} color={colors.textMuted}/><Text style={s.noteText}>Seus dados não serão compartilhados.</Text></View>
  </View>
 </View></ScrollView><Footer/></LinearGradient>
}
const s=StyleSheet.create({page:{flex:1},scroll:{flexGrow:1},layout:{width:'100%',maxWidth:1080,alignSelf:'center',paddingHorizontal:24,paddingVertical:72,flexDirection:'row',alignItems:'center',gap:80},layoutMobile:{flexDirection:'column',paddingVertical:48,gap:42},copy:{flex:1},iconBox:{width:48,height:48,borderRadius:15,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center',marginBottom:26},kicker:{color:colors.primary,fontSize:10,fontWeight:'800',letterSpacing:1.6,marginBottom:14},title:{color:colors.text,fontSize:46,lineHeight:52,fontWeight:'900',letterSpacing:-1.5},titleMobile:{fontSize:36,lineHeight:42},accent:{color:colors.primary},subtitle:{color:colors.textSecondary,fontSize:15,lineHeight:25,marginTop:18,maxWidth:480},steps:{marginTop:34,gap:14},step:{flexDirection:'row',alignItems:'center',gap:12},stepNumber:{color:colors.primary,fontSize:10,fontWeight:'900'},stepText:{color:colors.textSecondary,fontSize:12},card:{flex:1,width:'100%',maxWidth:480,backgroundColor:'rgba(16,31,50,.92)',borderWidth:1,borderColor:colors.border,borderRadius:24,padding:28,shadowColor:'#000',shadowOpacity:.3,shadowRadius:30},formTitle:{color:colors.text,fontSize:21,fontWeight:'800'},formSub:{color:colors.textMuted,fontSize:12,lineHeight:18,marginTop:6,marginBottom:26},label:{color:colors.textSecondary,fontSize:10,fontWeight:'800',letterSpacing:1.1,marginBottom:8},inputWrap:{minHeight:54,flexDirection:'row',alignItems:'center',gap:10,backgroundColor:colors.backgroundSoft,borderWidth:1,borderColor:colors.border,borderRadius:14,paddingHorizontal:14,marginBottom:18},input:{flex:1,color:colors.text,fontSize:14,outlineStyle:'none'} as any,textarea:{height:130,alignItems:'flex-start',paddingTop:15,marginBottom:6},textareaInput:{height:100},counter:{color:colors.textMuted,fontSize:10,textAlign:'right',marginBottom:18},button:{height:54,borderRadius:14,backgroundColor:colors.primary,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9},hover:{backgroundColor:'#57E5B5',transform:[{translateY:-2}]},pressed:{opacity:.75},buttonText:{color:'#06251B',fontSize:14,fontWeight:'800'},note:{flexDirection:'row',justifyContent:'center',alignItems:'center',gap:6,marginTop:16},noteText:{color:colors.textMuted,fontSize:10}});
