import { StyleSheet, View, Text, TextInput, Pressable, useWindowDimensions, ScrollView, ActivityIndicator } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { useState } from 'react';
import { collection, getDocs } from 'firebase/firestore';
import { db } from '../../src/backend/firebaseconfig';
import Header from '../header'; import Footer from '../footer'; import ModalScreen from '../modal'; import { AppColors } from '../theme'; import { useAppTheme } from '../../src/context/ThemeContext';

export default function HomeScreen() {
  const {colors,isDark}=useAppTheme(); const s=makeStyles(colors);
  const [busca,setBusca]=useState(''); const [modalVisible,setModalVisible]=useState(false); const [resultados,setResultados]=useState<any[]>([]); const [loading,setLoading]=useState(false);
  const {width}=useWindowDimensions(); const mobile=width<720;
  const carregar=async(todos=false)=>{if(!todos&&!busca.trim())return;setLoading(true);try{const snap=await getDocs(collection(db,'termos'));const termoBusca=busca.trim().toLocaleLowerCase('pt-BR');const lista:any[]=[];snap.forEach(d=>{const data=d.data();if(todos||(typeof data.termo==='string'&&data.termo.toLocaleLowerCase('pt-BR').includes(termoBusca)))lista.push(data)});setResultados(lista);setModalVisible(true)}catch(e){console.error('Erro na busca:',e)}finally{setLoading(false)}};
  return <View style={s.page}><LinearGradient colors={isDark?['#08111D','#0C1B28','#0D2730']:['#F8FBFC','#EEF5F4','#E5F1ED']} style={StyleSheet.absoluteFill}/><View style={s.orbOne}/><View style={s.orbTwo}/>
    <ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}><Header/>
      <View style={[s.hero,mobile&&s.heroMobile]}>
        <View style={s.copy}><View style={s.eyebrow}><View style={s.pulse}/><Text style={s.eyebrowText}>CONHECIMENTO SEM BARREIRAS</Text></View>
          <Text style={[s.title,mobile&&s.titleMobile]}>Tecnologia em{'\n'}<Text style={s.accent}>palavras simples.</Text></Text>
          <Text style={[s.subtitle,mobile&&s.subtitleMobile]}>Encontre definições claras para os termos que movem o mundo digital. Sem jargões, sem complicação.</Text>
          <View style={s.search}><Ionicons name="search" size={21} color={colors.textMuted}/><TextInput value={busca} onChangeText={setBusca} onSubmitEditing={()=>carregar()} placeholder="O que você quer entender?" placeholderTextColor={colors.textMuted} style={s.input} returnKeyType="search"/><Pressable accessibilityLabel="Buscar" onPress={()=>carregar()} style={({hovered,pressed})=>[s.searchBtn,hovered&&s.searchHover,pressed&&s.pressed]}>{loading?<ActivityIndicator color={colors.primaryText}/>:<Ionicons name="arrow-forward" size={21} color={colors.primaryText}/>}</Pressable></View>
          <View style={s.actions}><Pressable onPress={()=>carregar(true)} style={({hovered,pressed})=>[s.primary,hovered&&s.primaryHover,pressed&&s.pressed]}><Ionicons name="book-outline" size={18} color={colors.primaryText}/><Text style={s.primaryText}>Explorar dicionário</Text></Pressable><Text style={s.hint}>Busque por IA, cloud, API...</Text></View>
        </View>
        {!mobile&&<View style={s.visual}><View style={s.codeCard}><View style={s.codeTop}><View style={s.windowDots}><View style={[s.windowDot,{backgroundColor:'#FF7185'}]}/><View style={[s.windowDot,{backgroundColor:'#FFCA6A'}]}/><View style={[s.windowDot,{backgroundColor:colors.primary}]}/></View><Text style={s.file}>dicionario.tech</Text></View><View style={s.codeBody}><Text style={s.line}><Text style={s.muted}>01  </Text><Text style={s.blue}>const </Text><Text style={s.light}>tecnologia = </Text><Text style={s.green}>&apos;para todos&apos;</Text><Text style={s.light}>;</Text></Text><Text style={s.line}><Text style={s.muted}>02  </Text></Text><Text style={s.line}><Text style={s.muted}>03  </Text><Text style={s.blue}>function </Text><Text style={s.light}>entender(</Text><Text style={s.green}>termo</Text><Text style={s.light}>) {'{'}</Text></Text><Text style={s.line}><Text style={s.muted}>04    </Text><Text style={s.blue}>return </Text><Text style={s.green}>&apos;simples e claro&apos;</Text><Text style={s.light}>;</Text></Text><Text style={s.line}><Text style={s.muted}>05  </Text><Text style={s.light}>{'}'}</Text></Text></View></View><View style={s.floatBadge}><Ionicons name="sparkles" color={colors.primary} size={18}/><View><Text style={s.floatStrong}>Aprenda no seu ritmo</Text><Text style={s.floatSub}>Conteúdo direto ao ponto</Text></View></View></View>}
      </View>
      <View style={s.features}><View style={s.feature}><Ionicons name="flash-outline" size={20} color={colors.primary}/><View><Text style={s.featureTitle}>Rápido</Text><Text style={s.featureText}>Encontre em segundos</Text></View></View><View style={s.separator}/><View style={s.feature}><Ionicons name="chatbubble-ellipses-outline" size={20} color={colors.blue}/><View><Text style={s.featureTitle}>Acessível</Text><Text style={s.featureText}>Explicações sem jargões</Text></View></View><View style={s.separator}/><View style={s.feature}><Ionicons name="people-outline" size={20} color={colors.warning}/><View><Text style={s.featureTitle}>Colaborativo</Text><Text style={s.featureText}>Construído com a comunidade</Text></View></View></View>
      <Footer/>
    </ScrollView><ModalScreen visible={modalVisible} onClose={()=>setModalVisible(false)} termos={resultados}/>
  </View>;
}
const makeStyles=(colors:AppColors)=>StyleSheet.create({
 page:{flex:1,backgroundColor:colors.background},scroll:{flexGrow:1},orbOne:{position:'absolute',width:480,height:480,borderRadius:240,backgroundColor:'rgba(50,214,160,.05)',top:-180,right:-100},orbTwo:{position:'absolute',width:350,height:350,borderRadius:175,backgroundColor:'rgba(101,167,255,.045)',bottom:120,left:-160},
 hero:{width:'100%',maxWidth:1180,alignSelf:'center',minHeight:570,paddingHorizontal:24,paddingVertical:68,flexDirection:'row',alignItems:'center',gap:72},heroMobile:{minHeight:550,paddingVertical:48},copy:{flex:1,zIndex:2},eyebrow:{flexDirection:'row',alignItems:'center',gap:9,marginBottom:20},pulse:{width:8,height:8,borderRadius:4,backgroundColor:colors.primary},eyebrowText:{color:colors.primary,fontSize:14,fontWeight:'800',letterSpacing:1.2},title:{color:colors.text,fontSize:58,lineHeight:64,fontWeight:'900',letterSpacing:-2.2},titleMobile:{fontSize:39,lineHeight:45,letterSpacing:-1.3,textAlign:'center'},accent:{color:colors.primary},subtitle:{color:colors.textSecondary,fontSize:18,lineHeight:29,maxWidth:590,marginTop:22,marginBottom:30},subtitleMobile:{fontSize:16,lineHeight:25,textAlign:'center'},search:{height:66,maxWidth:610,flexDirection:'row',alignItems:'center',gap:12,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:18,paddingLeft:18,paddingRight:7,shadowColor:'#000',shadowOpacity:.08,shadowRadius:18},input:{flex:1,color:colors.text,fontSize:16,outlineStyle:'none'} as any,searchBtn:{width:50,height:50,borderRadius:14,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},searchHover:{backgroundColor:colors.primaryHover},actions:{flexDirection:'row',alignItems:'center',gap:18,marginTop:18,flexWrap:'wrap'},primary:{minHeight:48,borderRadius:14,paddingHorizontal:18,backgroundColor:colors.primary,flexDirection:'row',alignItems:'center',gap:9},primaryHover:{transform:[{translateY:-2}]},primaryText:{color:colors.primaryText,fontSize:15,fontWeight:'800'},hint:{color:colors.textMuted,fontSize:14},pressed:{opacity:.75},
 visual:{width:420,height:360,justifyContent:'center'},codeCard:{backgroundColor:colors.surface,borderRadius:22,borderWidth:1,borderColor:colors.border,overflow:'hidden',transform:[{rotate:'2deg'}],shadowColor:'#000',shadowOpacity:.18,shadowRadius:35,shadowOffset:{width:0,height:22}},codeTop:{height:50,backgroundColor:colors.backgroundSoft,borderBottomWidth:1,borderBottomColor:colors.border,flexDirection:'row',alignItems:'center',paddingHorizontal:17},windowDots:{flexDirection:'row',gap:7},windowDot:{width:9,height:9,borderRadius:5},file:{color:colors.textMuted,fontSize:14,marginLeft:'auto',marginRight:'auto'},codeBody:{padding:28,gap:12},line:{fontFamily:'monospace',fontSize:14},muted:{color:colors.textMuted},blue:{color:colors.blue},green:{color:colors.primary},light:{color:colors.text},floatBadge:{position:'absolute',left:-26,bottom:22,backgroundColor:colors.surfaceRaised,borderWidth:1,borderColor:colors.border,borderRadius:16,padding:14,flexDirection:'row',alignItems:'center',gap:10,shadowColor:'#000',shadowOpacity:.18,shadowRadius:20},floatStrong:{color:colors.text,fontSize:14,fontWeight:'700'},floatSub:{color:colors.textMuted,fontSize:14,marginTop:2},
 features:{width:'100%',maxWidth:1000,alignSelf:'center',paddingHorizontal:24,paddingVertical:30,marginBottom:64,borderTopWidth:1,borderBottomWidth:1,borderColor:colors.border,flexDirection:'row',justifyContent:'space-around',alignItems:'center',flexWrap:'wrap',gap:20},feature:{flexDirection:'row',alignItems:'center',gap:12,minWidth:180},featureTitle:{color:colors.text,fontSize:15,fontWeight:'700'},featureText:{color:colors.textMuted,fontSize:14,marginTop:3},separator:{width:1,height:32,backgroundColor:colors.border}
});
